name: 2019.4.40f1-Player

on:
  pull_request:
    branches:
      - main
  push:
    branches:
      - main

jobs:
  editor-tests:
    uses: ./.github/workflows/main.yml
    with:
      projectPath: './'
      unityVersion: '2019.4.40f1'
      testMode: 'playmode'
    secrets: inherit