name: 2020.3.40f1-Build

on:
  pull_request:
    branches:
      - main_disabled
  push:
    branches:
      - main_disabled

jobs:
  editor-tests:
    uses: ./.github/workflows/main.yml
    with:
      projectPath: './'
      unityVersion: '2020.3.40f1'
      testMode: 'standalone'
    secrets: inherit