name: Editor Tests

on:
  pull_request:
    branches:
      - master
  push:
    branches:
      - master

jobs:
  editor-tests:
    uses: ./.github/workflows/main.yml
    with:
      projectPath: './'
      unityVersion: '2020.3.40f1'
      testMode: 'editmode'
      unityEmail: ${{ secrets.UNITY_EMAIL }}
      unityPassword: ${{ secrets.UNITY_PASSWORD }}
      unityLicense: ${{ secrets.UNITY_LICENSE }}
      githubToken: ${{ secrets.GITHUB_TOKEN }}