name: 2021.3.45f1-Editor

on:
  pull_request:
    branches:
      - main
  push:
    branches:
      - main

jobs:
  editor-tests:
    uses: ./.github/workflows/main.yml
    with:
      projectPath: './'
      unityVersion: '2021.3.45f1'
      testMode: 'editmode'
    secrets: inherit