name: 2021.3.45f1-Build

on:
  pull_request:
    branches:
      - master_disabled
  push:
    branches:
      - master_disabled

jobs:
  editor-tests:
    uses: ./.github/workflows/main.yml
    with:
      projectPath: './'
      unityVersion: '2021.3.45f1'
      testMode: 'standalone'
    secrets: inherit