name: 2023.2.20f1-Build

on:
  pull_request:
    branches:
      - main_disabled
  push:
    branches:
      - main_disabled

jobs:
  editor-tests:
    uses: ./.github/workflows/main.yml
    with:
      projectPath: './'
      unityVersion: '2023.2.20f1'
      testMode: 'standalone'
    secrets: inherit