name: 2023.1.20f1-Player

on:
  pull_request:
    branches:
      - main_disabled
  push:
    branches:
      - main_disabled

jobs:
  editor-tests:
    uses: ./.github/workflows/main.yml
    with:
      projectPath: './'
      unityVersion: '2023.1.20f1'
      testMode: 'playmode'
    secrets: inherit