name: Editor Tests

on:
  workflow_call:
    inputs:
      projectPath:
        required: true
        type: string
      unityVersion:
        required: true
        type: string
      testMode:
        required: true
        type: string
    secrets:
      UNITY_LICENSE:
        required: true
      UNITY_EMAIL:
        required: true
      UNITY_PASSWORD:
        required: true

jobs:
  test:
    name: ${{ inputs.unityVersion }} ${{ inputs.testMode }}
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
        with:
          lfs: false
      - uses: actions/cache@v4
        with:
          path: ${{ inputs.projectPath }}/Library
          key: Library-${{ inputs.unityVersion }}
          restore-keys: |
            Library-
      - uses: game-ci/unity-test-runner@v4
        id: tests
        env:
          UNITY_LICENSE: ${{ secrets.UNITY_LICENSE }}
          UNITY_EMAIL: ${{ secrets.UNITY_EMAIL }}
          UNITY_PASSWORD: ${{ secrets.UNITY_PASSWORD }}
        with:
          projectPath: ${{ inputs.projectPath }}
          unityVersion: ${{ inputs.unityVersion }}
          testMode: ${{ inputs.testMode }}
          artifactsPath: ${{ inputs.testMode }}-artifacts
          githubToken: ${{ secrets.GITHUB_TOKEN }}
          checkName: ${{ inputs.unityVersion }} ${{ inputs.testMode }} Test Results