name: Editor Tests

on:
  pull_request:
    branches:
      - master
  push:
    branches:
      - master

jobs:
  testAllModes:
    name: ${{ matrix.unityVersion }} ${{ matrix.testMode }}
    runs-on: ubuntu-latest
    strategy:
      fail-fast: true
      matrix:
        projectPath:
          - './'
        unityVersion:
          - '2019.3.10f1'
          - '2019.4.40f1'
          - '2020.1.12f1'
          - '2020.3.40f1'
          - '2021.3.45f1'
          - '2022.3.57f1'
          - '2023.1.20f1'
          - '2023.2.20f1'
          - '6000.0.37f1'
        testMode:
          - editmode
    steps:
      - uses: actions/checkout@v4
        with:
          lfs: false
      - uses: actions/cache@v4
        with:
          path: ${{ matrix.projectPath }}/Library
          key: Library-${{ matrix.unityVersion }}
          restore-keys: |
            Library-
      - uses: game-ci/unity-test-runner@v4
        id: tests
        env:
          UNITY_LICENSE: ${{ secrets.UNITY_LICENSE }}
          UNITY_EMAIL: ${{ secrets.UNITY_EMAIL }}
          UNITY_PASSWORD: ${{ secrets.UNITY_PASSWORD }}
        with:
          projectPath: ${{ matrix.projectPath }}
          unityVersion: ${{ matrix.unityVersion }}
          testMode: ${{ matrix.testMode }}
          artifactsPath: ${{ matrix.testMode }}-artifacts
          githubToken: ${{ secrets.GITHUB_TOKEN }}
          checkName: ${{ matrix.unityVersion }} ${{ matrix.testMode }} Test Results

