name: Unity Editor Tests

on:
  pull_request:
    branches:
      - master

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Setup Unity
      uses: game-ci/unity-actions@v2
      with:
        unityVersion: '2020.3.48f1'

    - name: Run Unity Tests
      uses: game-ci/unity-test-runner@v2
      with:
        unityVersion: '2020.3.48f1'
        testMode: editmode
        artifactsPath: ${{ github.workspace }}/artifacts

    - name: Upload Test Artifacts
      uses: actions/upload-artifact@v2
      with:
        name: test-artifacts
        path: ${{ github.workspace }}/artifacts
